"""Added links table

Revision ID: 082b913d9f51
Revises: 
Create Date: 2026-01-22 22:02:09.517912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082b913d9f51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('url_final', sa.String(), nullable=False),
    sa.Column('url_original', sa.String(), nullable=False),
    sa.Column('campaign', sa.String(length=30), nullable=False),
    sa.Column('utm_source', sa.String(length=30), nullable=False),
    sa.Column('utm_medium', sa.String(length=30), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
