"""remove params

Revision ID: 6d2a86cc467d
Revises: 082b913d9f51
Create Date: 2026-01-24 10:39:42.557178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2a86cc467d'
down_revision: Union[str, Sequence[str], None] = '082b913d9f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'utm_medium')
    op.drop_column('links', 'campaign')
    op.drop_column('links', 'utm_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('utm_source', sa.VARCHAR(length=30), nullable=False))
    op.add_column('links', sa.Column('campaign', sa.VARCHAR(length=30), nullable=False))
    op.add_column('links', sa.Column('utm_medium', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
